apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: node-operator.v0.0.1
  namespace: placeholder
  annotations:
    alm-examples: >-
      [{"apiVersion":"","kind":"","metadata":{"name":""},"spec":{}},{"apiVersion":"","kind":"","metadata":{"name":""},"spec":{}},{"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"","metadata":{"name":"nodejs.demo.example.com"},"spec":{"group":"demo.example.com","names":{"kind":"Nodejs","listKind":"NodejsList","plural":"nodejs","singular":"nodejs"},"scope":"Namespaced","subresources":{"status":{}},"version":"v1alpha1","versions":[{"name":"v1alpha1","served":true,"storage":true}]}},{"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"","metadata":{"name":"nodejs.demo.example.com"},"spec":{"group":"demo.example.com","names":{"kind":"Nodejs","listKind":"NodejsList","plural":"nodejs","singular":"nodejs"},"scope":"Namespaced","subresources":{"status":{}},"version":"v1alpha1","versions":[{"name":"v1alpha1","served":true,"storage":true}]}},{"apiVersion":"","kind":"","metadata":{"name":""},"spec":{}},{"apiVersion":"","kind":"","metadata":{"name":""},"spec":{}},{"apiVersion":"","kind":"Nodejs","metadata":{"name":""},"spec":{}}]
    categories: Database
    certified: 'false'
    description: >-
      build and develop nodejs application and using operators for managing the
      application
    containerImage: ''
    support: ''
    capabilities: Seamless Upgrades
    repository: ''
spec:
  displayName: NodejsOperator
  description: |
    ## About the managed application
    ## About this Operator
    ## Prerequisites for enabling this Operator
  maturity: planning
  version: 0.0.1
  replaces: ''
  minKubeVersion: 1.11.0
  keywords: []
  maintainers:
    - name: ''
      email: ''
  provider:
    name: 'ACME,inc'
  labels: {}
  selector:
    matchLabels: {}
  links:
    - name: Blog
      url: >-
        https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAKgElEQVR4Xu2dX2wcRx3Hf3NO7CTun5CmTkxNKqq0RG4xKSKEBsW7xwM0qEUIhPj70Aq1/HlpnAcUqRJIgITaSEFFgNS8wEvhBcFLa0tUcDN3IZFJr4lCZEGkiLaB5k//kNgX22ff7aBde897692d3+zO7E2cu6fE95uZ3/w+8/39ZmfXawLdj1ERIEZ503UGukAMWwRdIF0ghkXAMHe6CukCMSwChrnTVUgXSIYIHJrgGVovNT16wOhFaLRzoAKAiKBhgMwDkgeEOEgGwDEDyNj4dSDkDtFizu37DoLpLJBOqgFDt9boh2OPz2JMVdl0BsjY+Fkg5KOqJqG9nxwVkz8Q01WRRDcHMPkBuZlBBCHV3uqFY99Z1KXKfICsFRhBCprUoh+IAhj26897oaAf/4GuhZmuXw1Q9AE5NHENAO5MN9P2Vj6QWwGKHiAKVOEjGXjv3PXhN8dbYMMqCcLCwL/Rd9fiqQe/vR5ji7ZRqBT1QBTCcAPSt3DdeeTci4Wo4DSbjQcrlcoUJnCWVawRAv1B27e3jsyf3/HoBkx7oY0iKGqBKIbhB6EtZdGStM+WVXyPENjipbzl9rZdbB1UKqtNCqBITy52pWiCYVWPOITwgh9I4UoNGfiBj2q/c+fOvqGhD827TS4M7q9fHHykT7b/VfYZoagB8sz4U9BDjmWeTDiYrz8PnMMfGSt9OU3fllX8HSHw9SAMyyrOMVbaGOzPh3buvi/W3938QEehqAGiUB1Z01Mw0JZVvEIIDIRhRqmlpSRVW+uUSskORAOMtOkpTkXBegHAN1JKvTQV/pgAJRuQmwCGG/SkOhJS1EuEwDe84q9CKY3Fe+EXX3hLJt2mB3Lwld1QKJyWGSzJdiVV8YcppWdU9Svbj/Ldl2TqSg9EoTq8Vbx8POIH0HH4C+UyPSgbUBX2nYSSDohiGFFA3J9dvXqlb2pqakFFkGX78KGcfOi7UO/NeDNTQiXGAsEU9uBKbjb5k5UK/a1s4BPT6PLFo5J6goQiD0SDOsIKwcDYs8fe3t9PLvkBxbSRhWVZ1tOEFF5UUuSbsAteOPAvkQ9GAVlYqG87ceLEVZHTwe9dleiA4Y+htJ4gVCIHRIM6Wvc6UpxRyYDLYutD+eeOR+cubx1pu8qX6td0IDcDjLBSMtcTARS8QhSqY/T0EafAeYFz57OMsVelVlmHjG3bXgdAvHvpmaB0CsjWa+dn6+tv3zTTP9gK4dDlyWs732abvUklpKjRUfvn5TId61DsY4f1U9diT9/i3z72TPqbXAlQtCjET0WcO88SQi5wTrwLvFpterRarbY9sdF+zpQMygRASs67MgORSFdp6gL2rMkEIJZVvEgIDGVKXaYDMSHQMj7oVAkuZSEVgr2XsTQh/i6l9G6ZQJhkmxlKjErEQMZe3g+kpywKhg/DcZovlcvlb8XZt11oGXztIbr49Ofx/m33zp994KvyD0qkBoJQR1zdiLuKvplqhnes03ogghcppVTJtUkeQPztrCjgllWcJwT6dB55iBQt8/3+/fYTPT3kN2F//XnWNtx947XhJ9seMRL3zx04+vmesJ04ZUkoZKVzvp5S2hA7tWRhWcU6IdArAajHtote/xJtsO5E2gnVnuYOY4RKMgPBFvLlwF8mBLbFRUY2uP4KnZmZ3lytVq9nirigsQgI230IeGGdnAs6gUgGs2DbxSYh8FipVHpFbhbt1j6UNCfFMuMmnSqn3nEZBEQmFkJbUc0SdiAw2Ldv30Bvb9+VuEWXH5Cxib8Agc8k+ZvmyjxrgMLtbdveCkDe0VVTMMBTQZFWiERBl0xZqpmgH/VJM3Bg2/thSukbUX0YAcQEdfjBwaziNDDcNpi+bdv+GQA5PNf7gdrkQ0/dhhpLtUJuBSAyJwvSKlmrQGSChlq5ASNM3+FbCOXdh8DBbIHXIhDM/RRMykmqC/53ojoZ9OXCPfbcxW2fTL7/Lg1kbKIEBOy4VdXplIWBEawBMruwcN9p2ybe7pUG8kRpA2yZnxMBAeBnKKUPhyePSw/8OUrpYZxt8KCvvYXoGgG7ypfmYP8egHwt7JNIIUH7tlQXd6wiDcQdIWHre8/V12bv/89fN2GDqcNOECTvREAGxt69e+/YuHHTqmMYGRjhnZ+nrigoqoG0Bg49KI1x3rbtTwCQU2kh4cZY+T1CzvmfGKNfShrPsopHCYHIhysw44nq0CoouoC4jux6Yxy2v3+u7fR1dNQ+XyiQ+4OOqji/WlmB9iKlNPLpD8sqvkkI7MAGMqpmBP3G9iMFRScQL/eGlJJ29c/MTPdXq9VVr0WyLOt7hBR+jSmwMjsrEQzMeKK5RtSUS3D0wAfD7TIfv4c7jIIiWl2WZU8TQm4XTUrUT1TuTgomBoRM/RH5j7mmEQM5OPE0FMB7Alz204ltcVKQHYf/A8D5ZqHQcxYzF3cBuP1xzkuM0cRDVkx/Xhbxf8Uh5nkCMRC3F8QhY5xDeUGRWe2Y4Pkwlmy5eyu9iGmHsUm6t6IdyPrGLHz67C8xfnbcZm5u9s7JycnpqNSHTZdZJ6EdSGtyigp+1glHteec1xijq2oYJuer9gcHJGPaajnNOdinj3j/lVlxqtNRMIhJfqx5IGnqSadgBAuwyp2WSFG5KcSH0Ww2BiqVine7FfPRBQSj0PDYnPN3GKOrXtWBmQfWBg8kQ9qSeVQo6Hhwi6gKDOfgMFZa9YBaVMCixuQc/sxY6XPYAMva5QoEsyrjgESlENnJph0/ahzZvrC+ygFJoZIdl07U77t03Hvlkcwk4i6gbLt4GSD+YbvwxDl3fsIY+yE2IL4dRpEy88GOrx1ImkIeVIOOSWOCgwGyvMjc1w9m/zMay07JA5FUSRogfjCaTf6VSoX+ARNA1TZYIKp3YEYDMV0d4UVQr88PnTx58r9ZFkc6IBIqESkkaSXeuMEHT52ibs3I9SOrjrBzWRZSeiBjE98HAr8SRUoEBFtE83ozUBYYnHPKWLZDyPRAkCrBApHd1mZZhUmLKB0QPkipGiVnA4KAoguIyjSBVamOMcN9ZgcigJIXkODEOHd+zBj7kSidBr+XUYYudbr+qAEyNn4aCNkdFwAXCuf8DGNLz25FfVafG0GDsZLw9RXYQEYFcXh4uHdgYFsdC45zmGaspOQPDMSNqQaIApWoOurGAsJC8O3y2lSoA5IABZO2/EA2GosfOX78+HnZgIXtR0ZG+rdsuauWtR+/vc40FfRRLZAYKCIgqtSBTYeykPKCoa6GhGcY8VBEEhTRkxiyAVQJxnH4ZLlMP6XKB1E/6hXijxiCYgIQ1zXLsv9OCNkjCkzeqcofTx8Qd4SD489CgfzU/eeuf7+8uP1/U96uKZgC8lJHGAC2+OeZrvSlrJgUFqWSTgFxXcRAWZtAlov9yhuD+OFymT4XDEreE/fXjAhK3n7pTVkRiTrqPnnekw66dcsD8VVBaWld3i+QSbP7ynux5K6QqNWZ96SxBZ5zWGCslP1PIGG3dMrOsiQGNNW0PXVxRimN/WVXnXPoqEJ0Tky2bxdIp5Wa37ZXNjq3sH1XIYbB7wLpAjEsAoa501VIF4hhETDMna5CDAPyf2qmgLAYU5k7AAAAAElFTkSuQmCC
    mediatype: image/png
  customresourcedefinitions:
    owned:
      - name: nodejs.demo.example.com
        displayName: Nodejs
        kind: Nodejs
        version: v1alpha1
        description: Nodejs
        resources:
          - version: v1
            kind: Deployment
          - version: v1
            kind: Service
          - version: v1
            kind: ReplicaSet
          - version: v1
            kind: Pod
          - version: v1
            kind: Secret
          - version: v1
            kind: ConfigMap
        specDescriptors: []
        statusDescriptors: []
    required: []
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: nodejs-operator
          rules:
            - apiGroups: '""'
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
      clusterPermissions:
        - serviceAccountName: nodejs-operator
          rules:
            - apiGroups: '""'
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
      deployments:
        - name: nodejs-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                k8s-app: nodejs-operator
            template:
              metadata:
                labels:
                  k8s-app: nodejs-operator
              spec:
                containers:
                  image: 'quay.io/deekshith_vemula/example:v1'
                  imagePullPolicy: Always
                  name: nodejs-operator
                  resources:
                    limits:
                      cpu: 200m
                      memory: 100Mi
                    requests:
                      cpu: 100m
                      memory: 50Mi
                  env:
                    - name: WATCH_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: OPERATOR_NAME
                      value: nodejs-operator
                imagePullSecrets:
                  - name: ''
                nodeSelector:
                  beta.kubernetes.io/os: linux
                serviceAccountName: nodejs-operator
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
