apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodejs.node.example.com
spec:
  group: node.example.com
  names:
    kind: Nodejs
    listKind: NodejsList
    plural: nodejs
    singular: nodejs
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
